name: govdesign_system
description: Biblioteca de componentes UI padronizados do design system gov.br.
version: 1.0.0
homepage: https://github.com/giancraft/ds-gov-temporario
repository: https://github.com/giancraft/ds-gov-temporario
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Rawline
      fonts:
        - asset: assets/fonts/rawline-400.ttf
        - asset: assets/fonts/rawline-700.ttf
          weight: 700
